Allow a request body to be a byte sequence/string
whatwg/fetch pull request #1083
Opened 2020-08-25 09:05 UTC by annevk

This simplifies things for several callers.

Fixes #1073.

2020-08-25 10:40 UTC, annevk commented
I think we could get rid of https://fetch.spec.whatwg.org/#concept-empty-readablestream too if we wanted to as it only has one caller and that might as well create a promise resolved with an empty byte sequence.

2020-08-25 16:32 UTC, domenic commented on fetch.bs
> +<p class="note no-backref">A <a for=/>byte sequence</a> and a <a for=/>scalar value string</a> will
```suggestion
<p class="note no-backref">A <a for=/>byte sequence</a> or a <a for=/>scalar value string</a> will
```

2020-08-25 16:37 UTC, domenic commented on fetch.bs
> +    <p>If <a><var>keepalive</var></a> is true, then <a>throw</a> a {{TypeError}}.
```suggestion
    <p>If <var>keepalive</var> is true, then <a>throw</a> a {{TypeError}}.
```

Only call sites link; inside the algorithm we just treat them as variables.

2020-08-25 16:59 UTC, annevk commented
I was thinking that since the note links "safely extract" it's clear it'll be UTF-8 and we don't really do anything else for strings these days (and shouldn't).

2020-08-25 17:16 UTC, domenic commented
That's reasonable. However, I'd still err on the side of removing the string possibility until we have more than one concrete caller that would use it. It appears the only user would be reporting, which would not get much simpler, because it would just switch from "serialize JSON to bytes" to... I guess manually using %JSON.stringify%?

2020-08-26 08:12 UTC, annevk commented
Fair, I'll drop that for now. @yutakahirano opinions on removing the empty ReadableStream primitive?

2020-08-26 08:27 UTC, annevk commented on fetch.bs
> +object, run these steps:
This needs rewording if we are to keep the "empty" construct.

2020-08-26 10:14 UTC, yutakahirano commented
I think we need to fix https://fetch.spec.whatwg.org/#dom-body-body too.

2020-08-26 10:22 UTC, annevk commented
@yutakahirano hey! What fix does that need? Do you think we need to preserve "empty"? Any other thoughts on this PR?

2020-08-26 10:35 UTC, yutakahirano commented
... or the body definition in https://whatpr.org/fetch/1083.html#request-class.

https://fetch.spec.whatwg.org/#concept-body-body expects the body to be a [body](https://fetch.spec.whatwg.org/#concept-body) or null, but with this change (concept) request's body is null or a [body](https://fetch.spec.whatwg.org/#concept-body) or a byte sequence.

2020-08-26 10:43 UTC, annevk commented
Isn't the byte sequence turned into a body well before the `Boxy` mixin gets hold of it? What about the other questions?

2020-08-26 10:55 UTC, yutakahirano commented
I'm not sure it is.

https://w3c.github.io/ServiceWorker/#on-fetch-request-algorithm creates a Request object from a concept request directly at step 21.3.2.

>
> Let requestObject be a new Request object associated with request and a new associated Headers object whose guard is "immutable".

I'm fine with removing https://fetch.spec.whatwg.org/#concept-empty-readablestream if it's unnecessary.

2020-08-26 10:59 UTC, yutakahirano commented
Ah I was wrong, that is covered by https://whatpr.org/fetch/1083/ad9a84a...ba5c0f3.html#fetching. Sorry for that.

2020-08-26 11:13 UTC, yutakahirano requested changes

2020-08-26 11:13 UTC, yutakahirano commented on fetch.bs
> +   <dd><p><a for=ReadableStream>Enqueue bytes</a> given <var>object</var> and <var>stream</var>.
We need to close the stream below.

2020-08-26 11:13 UTC, yutakahirano commented on fetch.bs
> +   <var>stream</var>.
ditto

2020-08-27 04:05 UTC, yutakahirano approved these changes
LGTM

2020-08-27 05:16 UTC, merged